# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:/Users/Joel/Documents/Sparkle-Average-Analysis/ui/main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(982, 746)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_top = QtGui.QGridLayout()
        self.gridLayout_top.setObjectName(_fromUtf8("gridLayout_top"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_top.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_file_name = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_file_name.setObjectName(_fromUtf8("lineEdit_file_name"))
        self.gridLayout_top.addWidget(self.lineEdit_file_name, 1, 0, 1, 1)
        self.pushButton_browse = QtGui.QPushButton(self.centralwidget)
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.gridLayout_top.addWidget(self.pushButton_browse, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_top, 0, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.widget = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_19 = QtGui.QGridLayout(self.widget)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_stimulus = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_stimulus.sizePolicy().hasHeightForWidth())
        self.groupBox_stimulus.setSizePolicy(sizePolicy)
        self.groupBox_stimulus.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_stimulus.setFont(font)
        self.groupBox_stimulus.setFlat(True)
        self.groupBox_stimulus.setObjectName(_fromUtf8("groupBox_stimulus"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_stimulus)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_stim_type = QtGui.QLabel(self.groupBox_stimulus)
        self.label_stim_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_stim_type.setFont(font)
        self.label_stim_type.setObjectName(_fromUtf8("label_stim_type"))
        self.gridLayout_12.addWidget(self.label_stim_type, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_stimulus, 1, 1, 1, 1)
        self.groupBox_threshold = QtGui.QGroupBox(self.widget)
        self.groupBox_threshold.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_threshold.setFont(font)
        self.groupBox_threshold.setFlat(True)
        self.groupBox_threshold.setObjectName(_fromUtf8("groupBox_threshold"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_threshold)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.doubleSpinBox_threshold = QtGui.QDoubleSpinBox(self.groupBox_threshold)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_threshold.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_threshold.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_threshold.setFont(font)
        self.doubleSpinBox_threshold.setDecimals(4)
        self.doubleSpinBox_threshold.setMinimum(-100.0)
        self.doubleSpinBox_threshold.setMaximum(100.0)
        self.doubleSpinBox_threshold.setSingleStep(0.001)
        self.doubleSpinBox_threshold.setObjectName(_fromUtf8("doubleSpinBox_threshold"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_threshold, 0, 0, 1, 1)
        self.pushButton_auto_threshold = QtGui.QPushButton(self.groupBox_threshold)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_auto_threshold.setFont(font)
        self.pushButton_auto_threshold.setObjectName(_fromUtf8("pushButton_auto_threshold"))
        self.gridLayout_4.addWidget(self.pushButton_auto_threshold, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_threshold, 2, 1, 1, 1)
        self.dockWidget_preview = QtGui.QDockWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidget_preview.sizePolicy().hasHeightForWidth())
        self.dockWidget_preview.setSizePolicy(sizePolicy)
        self.dockWidget_preview.setMinimumSize(QtCore.QSize(300, 150))
        self.dockWidget_preview.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_preview.setObjectName(_fromUtf8("dockWidget_preview"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.preview = TraceWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview.sizePolicy().hasHeightForWidth())
        self.preview.setSizePolicy(sizePolicy)
        self.preview.setObjectName(_fromUtf8("preview"))
        self.gridLayout_13.addWidget(self.preview, 0, 0, 1, 1)
        self.dockWidget_preview.setWidget(self.dockWidgetContents_2)
        self.gridLayout_2.addWidget(self.dockWidget_preview, 1, 0, 2, 1)
        self.gridLayout_19.addLayout(self.gridLayout_2, 2, 0, 1, 4)
        self.groupBox_raster_comments = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_raster_comments.sizePolicy().hasHeightForWidth())
        self.groupBox_raster_comments.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_raster_comments.setFont(font)
        self.groupBox_raster_comments.setFlat(True)
        self.groupBox_raster_comments.setObjectName(_fromUtf8("groupBox_raster_comments"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_raster_comments)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.lineEdit_comments = QtGui.QLineEdit(self.groupBox_raster_comments)
        self.lineEdit_comments.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_comments.sizePolicy().hasHeightForWidth())
        self.lineEdit_comments.setSizePolicy(sizePolicy)
        self.lineEdit_comments.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_comments.setFont(font)
        self.lineEdit_comments.setReadOnly(True)
        self.lineEdit_comments.setObjectName(_fromUtf8("lineEdit_comments"))
        self.gridLayout_18.addWidget(self.lineEdit_comments, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_raster_comments, 0, 3, 1, 1)
        self.groupBox_raster_test = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_raster_test.sizePolicy().hasHeightForWidth())
        self.groupBox_raster_test.setSizePolicy(sizePolicy)
        self.groupBox_raster_test.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_raster_test.setFont(font)
        self.groupBox_raster_test.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_raster_test.setFlat(True)
        self.groupBox_raster_test.setObjectName(_fromUtf8("groupBox_raster_test"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_raster_test)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.comboBox_test_num = QtGui.QComboBox(self.groupBox_raster_test)
        self.comboBox_test_num.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_test_num.sizePolicy().hasHeightForWidth())
        self.comboBox_test_num.setSizePolicy(sizePolicy)
        self.comboBox_test_num.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_test_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_test_num.setFont(font)
        self.comboBox_test_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_test_num.setObjectName(_fromUtf8("comboBox_test_num"))
        self.gridLayout_14.addWidget(self.comboBox_test_num, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_raster_test, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(34, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem, 0, 2, 1, 1)
        self.pushButtonAdd = QtGui.QPushButton(self.widget)
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.gridLayout_19.addWidget(self.pushButtonAdd, 5, 0, 1, 4)
        self.horizontalLayout_raster = QtGui.QHBoxLayout()
        self.horizontalLayout_raster.setObjectName(_fromUtf8("horizontalLayout_raster"))
        self.groupBox_raster_trace = QtGui.QGroupBox(self.widget)
        self.groupBox_raster_trace.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_raster_trace.setFont(font)
        self.groupBox_raster_trace.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_raster_trace.setFlat(True)
        self.groupBox_raster_trace.setObjectName(_fromUtf8("groupBox_raster_trace"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_raster_trace)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.comboBox_trace = QtGui.QComboBox(self.groupBox_raster_trace)
        self.comboBox_trace.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_trace.sizePolicy().hasHeightForWidth())
        self.comboBox_trace.setSizePolicy(sizePolicy)
        self.comboBox_trace.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_trace.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_trace.setFont(font)
        self.comboBox_trace.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_trace.setObjectName(_fromUtf8("comboBox_trace"))
        self.gridLayout_15.addWidget(self.comboBox_trace, 0, 0, 1, 1)
        self.horizontalLayout_raster.addWidget(self.groupBox_raster_trace)
        self.groupBox_raster_channel = QtGui.QGroupBox(self.widget)
        self.groupBox_raster_channel.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_raster_channel.setFont(font)
        self.groupBox_raster_channel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_raster_channel.setFlat(True)
        self.groupBox_raster_channel.setObjectName(_fromUtf8("groupBox_raster_channel"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_raster_channel)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.comboBox_channel = QtGui.QComboBox(self.groupBox_raster_channel)
        self.comboBox_channel.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_channel.sizePolicy().hasHeightForWidth())
        self.comboBox_channel.setSizePolicy(sizePolicy)
        self.comboBox_channel.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_channel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_channel.setFont(font)
        self.comboBox_channel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_channel.setObjectName(_fromUtf8("comboBox_channel"))
        self.gridLayout_17.addWidget(self.comboBox_channel, 0, 0, 1, 1)
        self.horizontalLayout_raster.addWidget(self.groupBox_raster_channel)
        self.gridLayout_19.addLayout(self.horizontalLayout_raster, 1, 0, 1, 4)
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 2, 2)
        self.gridLayout_bottom = QtGui.QGridLayout()
        self.gridLayout_bottom.setObjectName(_fromUtf8("gridLayout_bottom"))
        self.pushButtonReset = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonReset.sizePolicy().hasHeightForWidth())
        self.pushButtonReset.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonReset.setFont(font)
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.gridLayout_bottom.addWidget(self.pushButtonReset, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_bottom, 5, 0, 1, 2)
        self.dockWidget_view = QtGui.QDockWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidget_view.sizePolicy().hasHeightForWidth())
        self.dockWidget_view.setSizePolicy(sizePolicy)
        self.dockWidget_view.setMinimumSize(QtCore.QSize(300, 150))
        self.dockWidget_view.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_view.setObjectName(_fromUtf8("dockWidget_view"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_10 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.view = TraceWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view.sizePolicy().hasHeightForWidth())
        self.view.setSizePolicy(sizePolicy)
        self.view.setObjectName(_fromUtf8("view"))
        self.gridLayout_10.addWidget(self.view, 0, 0, 1, 1)
        self.dockWidget_view.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.dockWidget_view, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuShow = QtGui.QMenu(self.menuView)
        self.menuShow.setObjectName(_fromUtf8("menuShow"))
        self.menuHide = QtGui.QMenu(self.menuView)
        self.menuHide.setObjectName(_fromUtf8("menuHide"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtGui.QAction(MainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionView = QtGui.QAction(MainWindow)
        self.actionView.setCheckable(False)
        self.actionView.setChecked(False)
        self.actionView.setObjectName(_fromUtf8("actionView"))
        self.actionAttributes = QtGui.QAction(MainWindow)
        self.actionAttributes.setCheckable(False)
        self.actionAttributes.setChecked(False)
        self.actionAttributes.setAutoRepeat(True)
        self.actionAttributes.setMenuRole(QtGui.QAction.AboutQtRole)
        self.actionAttributes.setObjectName(_fromUtf8("actionAttributes"))
        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setCheckable(False)
        self.actionLog.setChecked(False)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionAll_show = QtGui.QAction(MainWindow)
        self.actionAll_show.setObjectName(_fromUtf8("actionAll_show"))
        self.actionAttributes_show = QtGui.QAction(MainWindow)
        self.actionAttributes_show.setObjectName(_fromUtf8("actionAttributes_show"))
        self.actionLog_show = QtGui.QAction(MainWindow)
        self.actionLog_show.setObjectName(_fromUtf8("actionLog_show"))
        self.actionView_show = QtGui.QAction(MainWindow)
        self.actionView_show.setObjectName(_fromUtf8("actionView_show"))
        self.actionAll_hide = QtGui.QAction(MainWindow)
        self.actionAll_hide.setObjectName(_fromUtf8("actionAll_hide"))
        self.actionAttributes_hide = QtGui.QAction(MainWindow)
        self.actionAttributes_hide.setObjectName(_fromUtf8("actionAttributes_hide"))
        self.actionLog_hide = QtGui.QAction(MainWindow)
        self.actionLog_hide.setObjectName(_fromUtf8("actionLog_hide"))
        self.actionView_hide = QtGui.QAction(MainWindow)
        self.actionView_hide.setObjectName(_fromUtf8("actionView_hide"))
        self.actionPreview_show = QtGui.QAction(MainWindow)
        self.actionPreview_show.setObjectName(_fromUtf8("actionPreview_show"))
        self.actionPreview_hide = QtGui.QAction(MainWindow)
        self.actionPreview_hide.setObjectName(_fromUtf8("actionPreview_hide"))
        self.menuShow.addAction(self.actionAll_show)
        self.menuShow.addSeparator()
        self.menuShow.addAction(self.actionAttributes_show)
        self.menuShow.addAction(self.actionLog_show)
        self.menuShow.addAction(self.actionView_show)
        self.menuShow.addAction(self.actionPreview_show)
        self.menuHide.addAction(self.actionAll_hide)
        self.menuHide.addSeparator()
        self.menuHide.addAction(self.actionAttributes_hide)
        self.menuHide.addAction(self.actionLog_hide)
        self.menuHide.addAction(self.actionView_hide)
        self.menuHide.addAction(self.actionPreview_hide)
        self.menuView.addAction(self.actionReset)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuShow.menuAction())
        self.menuView.addAction(self.menuHide.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionReset, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.show)
        QtCore.QObject.connect(self.actionView_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.show)
        QtCore.QObject.connect(self.actionView_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.hide)
        QtCore.QObject.connect(self.actionAll_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.show)
        QtCore.QObject.connect(self.actionAll_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.hide)
        QtCore.QObject.connect(self.actionAll_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_preview.show)
        QtCore.QObject.connect(self.actionAll_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_preview.hide)
        QtCore.QObject.connect(self.actionPreview_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_preview.show)
        QtCore.QObject.connect(self.actionPreview_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_preview.hide)
        QtCore.QObject.connect(self.actionReset, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_preview.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Average Analysis", None))
        self.label.setText(_translate("MainWindow", "Open:", None))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse...", None))
        self.groupBox_stimulus.setTitle(_translate("MainWindow", "Stimulus Type ", None))
        self.label_stim_type.setText(_translate("MainWindow", "None", None))
        self.groupBox_threshold.setTitle(_translate("MainWindow", "Threshold ", None))
        self.doubleSpinBox_threshold.setSuffix(_translate("MainWindow", " V", None))
        self.pushButton_auto_threshold.setText(_translate("MainWindow", "Estimate Threshold", None))
        self.dockWidget_preview.setWindowTitle(_translate("MainWindow", "Preview", None))
        self.groupBox_raster_comments.setTitle(_translate("MainWindow", "Comments ", None))
        self.groupBox_raster_test.setTitle(_translate("MainWindow", "Test Number ", None))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add To View", None))
        self.groupBox_raster_trace.setTitle(_translate("MainWindow", "Trace ", None))
        self.groupBox_raster_channel.setTitle(_translate("MainWindow", "Channel ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Average Analysis", None))
        self.pushButtonReset.setText(_translate("MainWindow", "Reset View", None))
        self.dockWidget_view.setWindowTitle(_translate("MainWindow", "View", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuShow.setTitle(_translate("MainWindow", "Show", None))
        self.menuHide.setTitle(_translate("MainWindow", "Hide", None))
        self.actionReset.setText(_translate("MainWindow", "Reset", None))
        self.actionView.setText(_translate("MainWindow", "View", None))
        self.actionAttributes.setText(_translate("MainWindow", "Attributes", None))
        self.actionLog.setText(_translate("MainWindow", "Log", None))
        self.actionAll_show.setText(_translate("MainWindow", "All", None))
        self.actionAttributes_show.setText(_translate("MainWindow", "Attributes", None))
        self.actionLog_show.setText(_translate("MainWindow", "Log", None))
        self.actionView_show.setText(_translate("MainWindow", "View", None))
        self.actionAll_hide.setText(_translate("MainWindow", "All", None))
        self.actionAttributes_hide.setText(_translate("MainWindow", "Attributes", None))
        self.actionLog_hide.setText(_translate("MainWindow", "Log", None))
        self.actionView_hide.setText(_translate("MainWindow", "View", None))
        self.actionPreview_show.setText(_translate("MainWindow", "Preview", None))
        self.actionPreview_hide.setText(_translate("MainWindow", "Preview", None))

from util.pyqtgraph_widgets import TraceWidget
